document.writeln("<link href=\'https://www.arsrna.cn/css/armain.css\' rel=\'stylesheet\'>");
document.writeln("<link href=\'https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("<script src=\'https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.1.3/js/bootstrap.min.js\'></script>");
document.writeln("<nav class=\'navbar fixed-top navbar-expand-lg navbar-light bg-light\'>");
document.writeln("    <div class=\'container-fluid\'>");
document.writeln("      <a class=\'navbar-brand\' href=\'#\'>Ar-Sr-Na AI技能中心</a>");
document.writeln("      <button class=\'navbar-toggler\' type=\'button\' data-bs-toggle=\'collapse\' data-bs-target=\'#navbarNavDropdown\' aria-controls=\'navbarNavDropdown\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("        <span class=\'navbar-toggler-icon\'></span>");
document.writeln("      </button>");
document.writeln("      <div class=\'collapse navbar-collapse\' id=\'navbarNavDropdown\'>");
document.writeln("        <ul class=\'navbar-nav\'>");
document.writeln("        <li class=\'nav-item active\'> <a class=\'nav-link\' href=\'#\'>主站 <span class=\'sr-only\'>(current)</span></a> </li>");
document.writeln("          <li class=\'nav-item\'> <a class=\'nav-link\' href=\'https://console.cloud.tencent.com/api/explorer\' target=\'_blank\'>腾讯云API中心</a> </li>");
document.writeln("          <li class=\'nav-item\'> <a class=\'nav-link\' href=\'https://ai.qq.com/\' target=\'_blank\'>腾讯AI开放中心</a> </li>");
document.writeln("");
document.writeln("");
document.writeln("          <li class=\'nav-item dropdown\'>");
document.writeln("            <a class=\'nav-link dropdown-toggle\' href=\'#\' id=\'products\' role=\'button\' data-bs-toggle=\'dropdown\' aria-expanded=\'false\'>");
document.writeln("              产品");
document.writeln("            </a>");
document.writeln("            <ul class=\'dropdown-menu\' aria-labelledby=\'products\'>");
document.writeln("               <h6 class=\'dropdown-header\'>图像、画面</h6>");
document.writeln("                <li><a class=\'dropdown-item\' href=\'ocr/\'>OCR</a></li>");
document.writeln("                <li><a class=\'dropdown-item\' href=\'face-beauty/\'>图像美化-美颜</a></li>");
document.writeln("           <div class=\'dropdown-divider\'></div>");
document.writeln("               <h6 class=\'dropdown-header\'>音视频识别</h6>");
document.writeln("               <li><a class=\'dropdown-item\' href=\'imglabel/\'>图像标签</a></li>");
document.writeln("            </ul>");
document.writeln("          </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </nav>");